### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by weijia-cheng** [dajare/anthony-trollope_the-prime-minister#1]
# Semantics

- [x] chapter-34: I think you should drop the `<span xml:lang="fr">` for “coup de grâce.” See [my post in the group](https://groups.google.com/g/standardebooks/c/20u9gG0a274) about why I think this should be the new standard.
- [x] chapter-9: In the title, you have `<abbr>No.</abbr> <span epub:type="ordinal z3998:roman">I</span>`. I think you should drop the `ordinal` because `ordinal` is for chapter numbers and such (per the EPUB 3 spec), which I don’t think this is. This will be consistent with what you already did in chapter-10 and the table of contents.
- [x] chapter-64 and chapter-66: I see some cases of `<abbr epub:type="z3998:initialism">K.G.</abbr>`. From my cursory research this seems to mean “Knight of the Garter” in the context of this book? In that case it should get a [`z3998:name-title`](https://standardebooks.org/manual/1.7.0/8-typography#8.10.5) semantic instead.
- [x] ~chapter-3 and chapter-78: “Q.C.” appears to be a similar case to “K.G.”~
- [x] chapter-66: I think the `<b>` in `<b>the</b> Duke` can be a `<strong>`. It seems like a strong emphasis rather than just an unsemantic formatting choice.

# Typos

- [x] chapter-32 and chapter-62: There seems to be a couple of instances where PG transcribed “Ruat c[oe]lum” for [“Ruat cælum.”](https://archive.org/details/cu31924086980947/page/216/mode/2up). You fixed the brackets but we still have PG’s misreading of the ligature. This appears to be a [stock phrase](https://en.wikipedia.org/wiki/Fiat_justitia_ruat_caelum) too. We should change the “o” to an “a.”

# Commit History

- [x] 8230b1ef6f301e315d4209c6542a7dc17153911a: You marked changing quoted titles to italicized titles as `[Editorial]` where you previously didn’t in manual semantication. I am not against that (I don’t typically make those changes as editorial changes) but it seems inconsistent to mark this commit as editorial when you previously included the same sorts of changes in non-editorial commits.

# CSS

- [x] Why not include the `font-variant: small-caps;` rule in the `table` selector and delete the `#chapter-34 table` selector? There’s only that one table in the text and it makes more sense to have all the table CSS in one place. 

# Metadata

- [x] Adolph Menzel should have a full name (Adolph Friedrich Erdmann von Menzel).

**Comment by dajare** [comment]
Thanks for another thorough and helpful review, Weijia! I think these are all done, and some comments:

### Semantics

- Re "K.G." - yes - just to note there is [one `name-title` instance (2 occurrences)](https://github.com/search?q=org%3Astandardebooks+%2F%28%3F-i%29title%22%3EK%5C.G%5C.%3C%2F&type=code), and [two `initialism` occurrences](https://github.com/search?q=org%3Astandardebooks+%2F%28%3F-i%29ism%22%3EK%5C.G%5C.%3C%2F&type=code). I've gone with `name-title`, as you advise.
- I have **left** "Q.C." as `initialism`, which is [much more common](https://github.com/search?q=org%3Astandardebooks+%2F%28%3F-i%29ism%22%3EQ%5C.C%5C.%3C%2F&type=code) in the corpus than [ the `name-title` version](https://github.com/search?q=org%3Astandardebooks+%2F%28%3F-i%29title%22%3EQ%5C.C%5C.%3C%2F&type=code). As I understand it, it is analogous to "M.P.", which is one of [the example "initialisms"](https://standardebooks.org/manual/1.7.0/8-typography#8.10.2) in SEMoS. Can revisit this, of course, but that's my sense of things at the moment.

###

- Metadata - I checked the corpus before adding the artist info, and [Menzel already appears](https://github.com/search?q=org%3Astandardebooks+%2FAdolph+Menzel%2F&type=code) as "Adolph Menzel". And that's the way he typically appears [in the secondary literature](https://scholar.google.com/scholar?hl=en&as_sdt=7,39&q=%22adolph+menzel%22). I'm happy to make the change, but have **left** as-is for the moment. Is there a reason for adopting the longer form? And if so, should the other instances in the corpus also be updated?

Thanks again!

**Comment by weijia-cheng** [comment]
Ok, let's just leave the Q.C. as is then.

For the artist, I wasn't referring to changing the main name, just adding `<meta property="se:name.person.full-name" refines="#artist">Adolph Friedrich Erdmann von Menzel</meta>` in addition to what already exists.

**Comment by dajare** [comment]
@weijia-cheng - re: artist — ahh! (Doh!) Right.

All done (+ an `se clean` change to local.css). 

re: Q.C. - thanks. I think that's right on this one. I did do some checking through the corpus on `name-title` and `initialism` and there are some odd discrepancies! If only I could `grep` them, it would be so much easier to see...... But, so far as I know, Github Code search doesn't (yet?) allow for export of results.
